import inquirer from 'inquirer';
const generateRandomNumber = () => Math.floor(Math.random() * 100) + 1;
const playGame = async () => {
    const randomNumber = generateRandomNumber();
    const userInput = await inquirer.prompt({
        type: 'number',
        name: 'userInputNumber',
        message: 'Please enter a number between 1 and 100:'
    });
    const { userInputNumber } = userInput;
    console.log('Number generated by the system:', randomNumber);
    console.log('Number input by the user:', userInputNumber);
    if (randomNumber === userInputNumber) {
        console.log("You won the game!");
    }
    else if (randomNumber < userInputNumber) {
        console.log("Your guess is too high.");
    }
    else {
        console.log("Your guess is too low.");
    }
};
playGame();
